services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"        # Host port from .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:     "${MYSQL_DATABASE}"
      MYSQL_USER:         "${MYSQL_USER}"
      MYSQL_PASSWORD:     "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"  # Host port from .env, falls back to 8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: "${MYSQL_USER}"         # auto-login as this user
      PMA_PASSWORD: "${MYSQL_PASSWORD}" # using the same password
volumes:
  db_data:
